
.text
.global _start
_start:
	/* Initialize gp for small-data accesses generated by GCC. */
	.option push
	.option norelax
	la gp, __global_pointer$
	.option pop

	/* Set up the kernel stack before calling any C code. */
	la sp, __stack_top

	/* Zero the NOLOAD BSS region (.bss/.sbss/COMMON). */
	la t0, __bss_start
	la t1, __bss_end
1:
	bgeu t0, t1, 2f
	sb zero, 0(t0)
	addi t0, t0, 1
	j 1b

2:
	/* Enter the kernel. */
	call kernel_main

	/* kernel_main should not return; if it does, park here. */
3:
	j 3b
