
.section .startup,"ax",@progbits
.global _start
_start:
	/*
	 * Put IRQ mask in a deterministic state at boot.
	 * 0x0605000b = picorv32_maskirq_insn(rd=x0, rs1=a0)
	 * a0 = -1 masks all IRQ sources until init_interrupts() unmasks timer.
	 */
	li a0, -1
	.word 0x0605000b
	j _start_init

	.section .text.startup_init,"ax",@progbits
_start_init:
	/* Materialize initialized small data at its low-memory runtime address. */
	la t0, __sdata_load_start
	la t1, __sdata_start
	la t2, __sdata_end
1:
	bgeu t1, t2, 2f
	lbu t3, 0(t0)
	sb t3, 0(t1)
	addi t0, t0, 1
	addi t1, t1, 1
	j 1b

	/* Zero the small BSS tail that shares the 4 KiB gp window. */
2:
	la t0, __sbss_start
	la t1, __sbss_end
3:
	bgeu t0, t1, 4f
	sb zero, 0(t0)
	addi t0, t0, 1
	j 3b

	/* Initialize gp for small-data accesses generated by GCC. */
	/* A 4 KiB window at address 0 needs gp at its midpoint (0x800). */
4:
	.option push
	.option norelax
	la gp, __global_pointer$
	.option pop

	/* Set up the kernel stack before calling any C code. */
	la sp, __stack_top

	/* Zero the regular NOLOAD BSS region (.bss/COMMON). */
	la t0, __bss_start
	la t1, __bss_end
5:
	bgeu t0, t1, 6f
	sb zero, 0(t0)
	addi t0, t0, 1
	j 5b

	/* Enter the kernel. */
6:
	call kernel_main

	/* kernel_main should not return; if it does, park here. */
	/* Keep the core halted if the C entry unexpectedly returns. */
7:
	j 7b
